### ISSUE TITLE
l.Logger undefined (type *negroni.Logger has no field or method Logger)

### ISSUE THREAD

**Issue by wpalmer** [almir/docker-webhook#1]
Failing to build against latest alpine, as of a couple of weeks ago. Not sure if this is an upstream problem.
I am able to build webhook via my local machine, it's only within "docker build" that I have issue.

Build output attached: [output.txt](https://github.com/almir/docker-webhook/files/462546/output.txt)

**Comment by almir** [comment]
This has been resolved upstream.
