### ISSUE TITLE
Any ideas on how to trigger a script on the host (not in the container)

### ISSUE THREAD

**Issue by pascalandy** [almir/docker-webhook#13]
Hi,

I found your project and it's very promising :) I want to use webhook to run cmd on the host. 

Because I run it in a container, there is a challenge. This is not a question regarding this repo but and overall question regarding docker permissions in general. Here is my use case.

When the webhook triggers, I want to run a script **on the host itself** (not in the container). Do you know how to do this?

In the logs you can see `unable to locate command: 'source /user/deploy-setup/cmd.sh; fct_noti_test'`

### run

```
docker run -d \
  --name=webhook \
  -p 9000:9000 \
  -v /user/project/webhooks:/etc/webhook \
  devmtl/webhook:2.6.9_2019-08-26_16H31s18_4cd1f08 \
  webhook -verbose -hooks=/etc/webhook/noti_test.json -hotreload
```

### logs
 
```
root@kara2:~# docker logs -f 7c5313d9d01d
[webhook] 2019/08/26 20:36:50 version 2.6.9 starting
[webhook] 2019/08/26 20:36:50 setting up os signal watcher
[webhook] 2019/08/26 20:36:50 attempting to load hooks from /etc/webhook/noti_test.json
[webhook] 2019/08/26 20:36:50 found 1 hook(s) in file
[webhook] 2019/08/26 20:36:50 	loaded: noti_test
[webhook] 2019/08/26 20:36:50 setting up file watcher for /etc/webhook/noti_test.json
[webhook] 2019/08/26 20:36:50 serving hooks on http://0.0.0.0:9000/hooks/{id}
[webhook] 2019/08/26 20:36:50 os signal watcher ready
[webhook] 2019/08/26 20:37:15 [83cf3e] incoming HTTP request from $IP:58702
[webhook] 2019/08/26 20:37:15 [83cf3e] noti_test got matched
[webhook] 2019/08/26 20:37:15 [83cf3e] noti_test hook triggered successfully
[webhook] 2019/08/26 20:37:15 200 | 419.624µs | $IP:9000 | GET /hooks/noti_test
[webhook] 2019/08/26 20:37:15 unable to locate command: 'source /user/deploy-setup/cmd.sh; fct_noti_test'
[webhook] 2019/08/26 20:37:15 use 'pass-arguments-to-command' to specify args for 'source'
```

Many thanks!

**Comment by bkmeneguello** [comment]
Docker comands only runs inside container. You need to mount you script as a volume and ensure all dependencies are met and environment variables are available

**Comment by pascalandy** [comment]
Alright. I was just wondering if you knew a hack to do this. Cheers!

**Comment by raitucarp** [comment]
I have suggestion you put something like port mapping
```
extra_hosts:
      - "thehost:172.31.30.231"
```

where 172.31.30.231 is your host ip, so the hooks can trigger host webhook, the flow something like this, host ip / domain => trigger webhook docker => trigger webhook on host => run script

**Comment by pascalandy** [comment]
@raitucarp: I found a tiny line of docs here: https://docs.docker.com/compose/compose-file/#extra_hosts

But there are not docs on the `docker run` section. Any ideas?

**Comment by raitucarp** [comment]
@pascalandy 

correct me if im wrong, extra_hosts is equivalent with --add-host

**Comment by pascalandy** [comment]
It makes sense, so I would go like this:

```
docker run -d \
  --name=webhook \
  --add-host="thehost:172.31.30.231" \
  -p 9000:9000 \
  -v /user/project/webhooks:/etc/webhook \
  devmtl/webhook:2.6.9_2019-08-26_16H31s18_4cd1f08 \
  webhook -verbose -hooks=/etc/webhook/noti_test.json -hotreload
```

[I the docs](https://docs.docker.com/engine/reference/commandline/run/) I also can see:

```
$ docker run --add-host=docker:10.180.0.1 --rm -it debian

root@f38c87f2a42d:/# ping docker
PING docker (10.180.0.1): 48 data bytes
56 bytes from 10.180.0.1: icmp_seq=0 ttl=254 time=7.600 ms
56 bytes from 10.180.0.1: icmp_seq=1 ttl=254 time=30.705 ms
^C--- docker ping statistics ---
2 packets transmitted, 2 packets received, 0% packet loss
round-trip min/avg/max/stddev = 7.600/19.152/30.705/11.553 ms
```

I'm not sure about the syntax. Should it be `docker` or `thehost`?

ps: I can't try it at the moment.

**Comment by ahamill85** [comment]
If anyone is looking for help on this topic, I found some guidance on this SO thread. It uses a unix pipe in order to pass commands to your docker host.

https://stackoverflow.com/a/63719458
