### ISSUE TITLE
How can we do an healthcheck?

### ISSUE THREAD

**Issue by pascalandy** [almir/docker-webhook#15]
I'd like to know if you can ensure the container is responding as it should by using Healthcheck.

At the end, we just to know you how the container can answer an EXIT=0.

Thanks!

**Comment by almir** [comment]
You can add healthcheck yourself when specifying your Dockerfile, before the `CMD` line.
For example:
```shell
FROM almir/webhook
COPY hooks.json.example /etc/webhook/hooks.json
HEALTHCHECK CMD curl --fail http://localhost:9000/ || exit 1
CMD ["-verbose", "-hooks=/etc/webhook/hooks.json", "-hotreload"]
```

**Comment by pascalandy** [comment]
Thanks!

I was looking for this specifically: `curl --fail http://localhost:9000/ || exit 1`
