### ISSUE TITLE
[Q] How to use webhook docker properly?

### ISSUE THREAD

**Issue by kkumar326** [almir/docker-webhook#17]
Hi,

I am a bit confused about how to use webhook docker properly. Now, triggering shell script on the host from webhook container is not possible. And triggering webhook in the container itself doesn't make sense.

What would be the proper use cases for this docker image?

Thanks!

**Comment by almir** [comment]
This is totally up to you and your needs/environment. Some hints here: https://github.com/almir/docker-webhook/issues/13
