### ISSUE TITLE
Add support for arm64

### ISSUE THREAD

**Issue by Skallwar** [almir/docker-webhook#25]
Webhook is working on arm64. Is it possible to push an arm64 version of this image?

This can be done like [this](https://github.com/ckulka/docker-multi-arch-example)

**Comment by almir** [comment]
Docker image as of now is being built for the following architectures:
- linux/386
- linux/amd64
- linux/arm/v6
- linux/arm/v7
- linux/arm64/v8

![image](https://github.com/almir/docker-webhook/assets/772884/2544b2ce-da0b-456b-8d6c-f88af101c999)
