### ISSUE TITLE
Cannot launch script that uses curl since curl is missing from docker build

### ISSUE THREAD

**Issue by psmith3** [almir/docker-webhook#5]
I need another set of eyes on my problem. I am trying to launch a simple script with a curl command to do a get on an IFTTT web hook. I have my hooks.json file launching the script successfully, but finally came to the realization that curl is not installed in the build. Is there an alternative in this build to curl that would launch a URL get to IFTTT? I have opened a shell into the running docker image and tried to install curl into the running image, but that will not work either. Any ideas?

**Comment by stefancrain** [comment]
I've confirmed this missing in the base image. 
```
$ docker exec -it {docker_webhook_container_name) /bin/sh
/ # curl
/bin/sh: curl: not found
```
But I do see that `wget` is included.

As mentioned in the README you can create your own image. 
```
FROM        almir/webhook
RUN         apk add --update curl && \
            rm -rf /var/cache/apk/*
COPY        hooks.json.example /etc/webhook/hooks.json
CMD         ["-verbose", "-hooks=/etc/webhook/hooks.json", "-hotreload"]
```
