### ISSUE TITLE
/bin/sh: curl: not found

### ISSUE THREAD

**Issue by towry** [almir/docker-webhook#8]
Dockerfile:

```dockerfile
FROM almir/webhook

RUN curl -fsSL get.docker.com -o get-docker.sh && sh get-docker.sh

COPY hooks.json /etc/webhook/hooks.json
CMD ["-verbose", "-hooks=/etc/webhook/hooks.json", "-hotreload", "-urlprefix=_webhook", "-port=9000"]

EXPOSE 9000

```

**Comment by almir** [comment]
This, actually, is the intended behavior. We do not pack anything else in this docker image except for the `webhook` binary itself. In case you need anything else, like `curl`, `bash` etc. just install it by running `apk add packagename` in your Dockerfile.
